version: '2'

services:
  sniproxy-service:
    image: sniproxy-dns:latest
    container_name: test
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    - ./tmp:/tmp
    - ./config:/app/config/
    restart: always
